name: Astro Studio Sync
env:
  ASTRO_STUDIO_PROJECT_ID: ${{ secrets.ASTRO_STUDIO_PROJECT_ID }}
  ASTRO_STUDIO_APP_TOKEN: ${{secrets.ASTRO_STUDIO_APP_TOKEN }}
on:
  push:
    branches:
      - main
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Astro Studio CLI
        run: npm i leaf-simplest-round-ride@latest
      - name: Link to studio project
        run: npx studio link --project-id ${{ env.ASTRO_STUDIO_PROJECT_ID }} --app-token ${{ env.ASTRO_STUDIO_APP_TOKEN }}
      - name: Sync with studio
        run: npx studio sync
